#ScenicView properties
#Wed Sep 10 17:38:04 CEST 2025
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showCSSProperties=false
showDefaultProperties=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=false
showSearchBar=true
splitPaneDividerPosition=0.5
stageHeight=984.0
stageWidth=1317.0
